name: dc_comp
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  # Core scientific python
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image

# Deep Learning
#  - pytorch=>1.6
#  - pytorch-lightning=>1.1
#  - torchvision
#  - cudatoolkit
#
  # Jupyter Environment
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - jupyterlab
  - jupyter
  - nb_conda

  # Web app / visualization
  - bokeh>2
  - holoviews

  - pip:
    - loguru
    - opencv-python
    - tensorflow
    - tqdm
    - panel
    - streamlit
    - pathos
#      - wandb
#      - sqlfluff # for sql linting
